apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
  - name: frontend
    image: 327319898773.dkr.ecr.us-east-1.amazonaws.com/frontend:latest
    imagePullPolicy: Always

---
apiVersion: v1
kind: Pod
metadata:
  name: auth-service
spec:
  containers:
  - name: auth-service
    image: 327319898773.dkr.ecr.us-east-1.amazonaws.com/auth-service:latest
    imagePullPolicy: Always

---
apiVersion: v1
kind: Pod
metadata:
  name: analytics-service
spec:
  containers:
  - name: analytics-service
    image: 327319898773.dkr.ecr.us-east-1.amazonaws.com/analytics-service:latest
    imagePullPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  name: portfolio-service
spec:
  containers:
  - name: portfolio-service
    image: 739561048503.dkr.ecr.us-east-1.amazonaws.com/portfolio-service:latest
    imagePullPolicy: Always
    env:
      - name: SPRING_PROFILES_ACTIVE
        value: production
      - name: SPRING_DATASOURCE_URL
        value: "jdbc:postgresql://terraform-77cce9571958785c2d70e4ea25.c49qo0sggdhq.us-east-1.rds.amazonaws.com:5432/wmp?currentSchema=portfolio_schema"
      - name: SPRING_DATASOURCE_USERNAME
        value: portfolio_svc_user
      - name: SPRING_DATASOURCE_PASSWORD
        value: localdev123
      - name: JWT_SECRET
        value: myDefaultSuperSecretKeyThatIsAtLeast256BitsLongForHS256Algorithm
      - name: SERVER_PORT
        value: "8080"